# Generated by Django 3.1.7 on 2021-03-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor_inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Helmet', models.CharField(max_length=20)),
                ('Chestplate', models.CharField(max_length=20)),
                ('Leggings', models.CharField(max_length=20)),
                ('Boot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Xp', models.IntegerField()),
                ('PosX', models.FloatField()),
                ('PosY', models.FloatField()),
                ('PosZ', models.FloatField()),
                ('Armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armor_inv')),
            ],
        ),
    ]
