# Generated by Django 3.1.7 on 2021-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
