# Generated by Django 3.1.7 on 2021-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='PosX',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosY',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosZ',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='Xp',
            field=models.CharField(max_length=50),
        ),
    ]
