# Generated by Django 3.1.7 on 2021-03-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Armor_inv',
        ),
    ]
