# Generated by Django 3.1.7 on 2021-03-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Boot',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='Chestplate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='Helmet',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='Leggings',
            field=models.CharField(default='', max_length=20),
        ),
    ]
