# Generated by Django 3.1.7 on 2021-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210305_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='PosX',
            field=models.DecimalField(decimal_places=14, max_digits=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosY',
            field=models.DecimalField(decimal_places=14, max_digits=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosZ',
            field=models.DecimalField(decimal_places=14, max_digits=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='Xp',
            field=models.IntegerField(),
        ),
    ]
