# Generated by Django 3.1.7 on 2021-03-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210306_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='PosX',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosY',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='PosZ',
            field=models.CharField(default='', max_length=100),
        ),
    ]
